config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # root "home#index"
  root "friends#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this firend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:frist_name, :last_name, :email, :phone, :address, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div class="alert">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="mb-3">
      <%= form.label :frist_name, class:"form-label" %>
      <%= form.text_field :frist_name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :last_name, class:"form-label" %>
      <%= form.text_field :last_name, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email, class:"form-label" %>
      <%= form.text_field :email, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :phone, class:"form-label" %>
      <%= form.text_field :phone, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :address, class:"form-label" %>
      <%= form.text_field :address, class:"form-control" %>
    </div>
     <div class="mb-3">
      <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
    </div>
    <br>
    <%= form.submit class:"btn btn-secondary" %>
  </form>

<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <h1><%= friend.frist_name %> <%= friend.last_name %></h1>

  <br>
  
    <strong>Frist name:</strong>
    <%= friend.frist_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= friend.address %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "View", @friend, class:"text-decoration-none" %> | 
  <%= link_to "Delete", @friend, method: :delete, data: { confirm: 'Are you sure?'}, class:"text-danger text-decoration-none" %>
  <br>
  <%= link_to "Back", friends_path, class:"text-decoration-none" %>
</div>

app/views/friends/index.html.erb
<h1>Friend List</h1>
<br>
<% if user_signed_in? %>
<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user%>
      <tr>
        <td><%= friend.id %></td>
        <td>
        <%= link_to friend.frist_name + " " + friend.last_name, friend, class:"text-decoration-none" %>
        </td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.address %></td>
        <% if friend.user == current_user %>
          <td class="d-flex flex-row gap-2">
          <%= link_to "Edit", edit_friend_path(friend), class:"btn btn-sm btn-secondary" %>
          <%= link_to "Delete", friend, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-sm btn-outline-danger" %>
          </td> 
        <% else %>
          <td></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Add New", new_friend_path, class:"btn btn-secondary"%>

<% else %>
  <h2>Login to explore more<h2>

<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class:"text-decoration-none" %>
</div>

app/views/friends/show.html.erb
<div class="container bg-light p-3 mb-3">
 <%= render @friend %>

  <div class="d-flex flex-row mb-3 gap-2">
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary"%>
  </div>

</div>

<%= link_to "< Back", friends_path, class:"text-decoration-none" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
           <%= link_to "Friends", friends_path, class:"nav-link"%>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to "Add Friends", new_friend_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-link nav-link"%>
            </li>
            <li class="nav-item">
            <%= link_to "Profile", edit_user_registration_path, class:"nav-link"%>
            </li>
        <% else %>
            <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
            <%= link_to "Login", user_session_path, class:"nav-link"%>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Friends APP</h1>
 

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends APP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "home/header" %>
    <div class="container mt-5">
      <% if notice %>
        <%= render "layouts/alerts" %>
      <% end %>
      
      <br>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>